/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        saffron: {
          50: "#FFF7ED",
          100: "#FFEDD5",
          200: "#FED7AA",
          300: "#FDBA74",
          400: "#FF9933",
          500: "#F97316",
          600: "#EA6A0A",
          700: "#C2500A",
          800: "#9A3E12",
          900: "#7C3512",
        },
        india: {
          50: "#F2FBEF",
          100: "#DFF5D8",
          200: "#BFEBB2",
          300: "#94DB80",
          400: "#62C74A",
          500: "#35AE1D",
          600: "#1E9B0E",
          700: "#138808",
          800: "#0F6D07",
          900: "#0B5205",
        },
        chakra: {
          50: "#EEF1FF",
          100: "#DDE3FF",
          200: "#BCC7FF",
          300: "#93A4FF",
          400: "#6B80FB",
          500: "#4A5EF0",
          600: "#2F41D6",
          700: "#1B2BA8",
          800: "#0D1A80",
          900: "#000080",
          950: "#05063D",
        },
        ink: {
          0: "#FFFFFF",
          50: "#F7F8FB",
          100: "#EEF0F6",
          200: "#DFE2EC",
          300: "#C4C9D8",
          400: "#9298AE",
          500: "#6B7189",
          600: "#4E5468",
          700: "#383D4E",
          800: "#232734",
          900: "#14161F",
          950: "#0B0C12",
        },
        rust: { 300: "#F79A92", 400: "#F2564B", 500: "#E03A2F", 600: "#C42718", 700: "#9E1C10" },

        canvas: "var(--canvas)",
        surface: { DEFAULT: "var(--surface)", 2: "var(--surface-2)", 3: "var(--surface-3)" },
        line: { DEFAULT: "var(--line)", strong: "var(--line-strong)" },
        body: { DEFAULT: "var(--text)", 2: "var(--text-2)", 3: "var(--text-3)" },
        brand: {
          DEFAULT: "var(--brand)",
          soft: "var(--brand-soft)",
          line: "var(--brand-line)",
          ink: "var(--brand-ink)",
        },
        proof: { DEFAULT: "var(--proof)", soft: "var(--proof-soft)", line: "var(--proof-line)" },
        unproven: { DEFAULT: "var(--unproven)", soft: "var(--unproven-soft)", line: "var(--unproven-line)" },
        blocker: { DEFAULT: "var(--blocker)", soft: "var(--blocker-soft)", line: "var(--blocker-line)" },
        absent: { DEFAULT: "var(--absent)", soft: "var(--absent-soft)", line: "var(--absent-line)" },
      },
      fontFamily: {
        display: ['"Instrument Serif"', "Georgia", "serif"],
        sans: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
      },
      borderRadius: { card: "14px", tile: "11px", pill: "999px" },
      boxShadow: {
        card: "var(--shadow-card)",
        lift: "var(--shadow-lift)",
      },
      keyframes: {
        stampIn: {
          "0%": { opacity: "0", transform: "scale(1.5) rotate(-14deg)" },
          "60%": { opacity: "1", transform: "scale(.94) rotate(2deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(-1.2deg)" },
        },
        segPulse: {
          "0%": { boxShadow: "0 0 0 0 rgb(19 136 8 / .55)" },
          "100%": { boxShadow: "0 0 0 12px transparent" },
        },
        spokeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        rise: { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "none" } },
        barPulse: {
          "0%,100%": { transform: "scaleY(.3)", opacity: ".5" },
          "50%": { transform: "scaleY(1)", opacity: "1" },
        },
      },
      animation: {
        stamp: "stampIn .42s cubic-bezier(.2,.9,.25,1.2) both",
        pulse1: "segPulse .85s ease-out 2",
        spoke: "spokeIn .5s ease both",
        rise: "rise .5s cubic-bezier(.2,.7,.3,1) forwards",
        bar: "barPulse 1.05s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
