import { useEffect } from "react";
import { useParams } from "react-router-dom";
import { CallDetailPage } from "./CallDetailPage";
import { PageSkeleton } from "@/components/ui/Skeleton";
import { EmptyState, ErrorState } from "@/components/ui/EmptyState";
import { EvidenceFocusProvider } from "@/components/evidence/EvidenceFocusContext";
import { AudioPlayerProvider } from "@/components/audio/AudioPlayerProvider";
import { useSharedReport, useCallAudioSrc, useCalls } from "@/hooks/useCallApi";
import { RealityCheckSection } from "@/features/reality-check/RealityCheckSection";
import { ProofRing, SignalBoard } from "@/features/signals/ProofRing";
import { EvidenceReceipt } from "@/components/evidence/EvidenceReceipt";
import { deriveDimensions, resolveSegment } from "@/lib/evidence";
import { pickDemoCall } from "@/features/demo/resolveDemoTarget";
import { CUSTOMER_TRUTH_CATEGORIES, type CallReport, type Transcript } from "@/api/contracts";

export function SharedPage() {
  const { token = "" } = useParams();
  const shared = useSharedReport(token);

  useEffect(() => {
    const wasDark = document.documentElement.classList.contains("dark");
    document.documentElement.classList.remove("dark");
    return () => {
      document.documentElement.classList.toggle("dark", wasDark);
    };
  }, []);

  if (shared.isLoading) return <PageSkeleton />;
  if (shared.isError || !shared.data) {
    return (
      <ErrorState
        title="Share link invalid"
        description={
          shared.error instanceof Error
            ? shared.error.message
            : "This report is missing, expired, revoked, or not ready yet."
        }
      />
    );
  }

  return <SharedReportView report={shared.data.report} transcript={shared.data.transcript} />;
}

function SharedReportView({ report, transcript }: { report: CallReport; transcript: Transcript }) {
  const audioSrc = useCallAudioSrc(report.call.id);
  const tiles = deriveDimensions(report);
  const factsWithEvidence = CUSTOMER_TRUTH_CATEGORIES.flatMap((category) =>
    report.customerTruth.filter((fact) => fact.category === category && fact.evidence.segmentIds.length),
  ).slice(0, 4);

  return (
    <EvidenceFocusProvider>
      <AudioPlayerProvider src={audioSrc} callDurationMs={report.call.durationMs}>
        <div className="page narrow">
          <div className="card pad-lg reveal" style={{ marginBottom: 16 }}>
            <div className="tiranga" style={{ height: 3, borderRadius: 9, overflow: "hidden", marginBottom: 16 }}>
              <i />
              <i />
              <i />
            </div>
            <div className="between" style={{ flexWrap: "wrap", gap: 10 }}>
              <div>
                <div className="eyebrow" style={{ marginBottom: 6 }}>
                  Shared call report · read only
                </div>
                <div className="serif" style={{ fontSize: 30, letterSpacing: "-.02em" }}>
                  {report.call.customerName.split("·")[1]?.trim() || report.call.customerName} — {report.call.title.toLowerCase()}
                </div>
                <div className="sub" style={{ marginTop: 4 }}>
                  {report.call.customerName} · {report.call.repName}
                </div>
              </div>
              <ProofRing tiles={tiles} />
            </div>
            <p className="invariant" style={{ marginTop: 14 }}>
              No proof in the transcript, no claim in this report.
            </p>
          </div>
          <div className="card pad-lg" style={{ marginBottom: 16 }}>
            <div className="h-sec" style={{ marginBottom: 11 }}>
              What the customer actually said
            </div>
            <div className="vstack" style={{ gap: 10 }}>
              {factsWithEvidence.map((fact) => {
                const segment = resolveSegment(transcript, fact.evidence.segmentIds[0]);
                return (
                  <div key={fact.id}>
                    <div style={{ fontWeight: 800, fontSize: 13.5, marginBottom: 5 }}>
                      {fact.category.replace("_", " ")} — {fact.title}
                    </div>
                    <EvidenceReceipt segment={segment} transcript={transcript} compact />
                  </div>
                );
              })}
            </div>
          </div>
          <div style={{ marginBottom: 16 }}>
            <RealityCheckSection checks={report.realityChecks.slice(0, 1)} transcript={transcript} />
          </div>
          <div className="card pad-lg">
            <div className="h-sec" style={{ marginBottom: 11 }}>
              Where this deal stands
            </div>
            <SignalBoard tiles={tiles} />
            <div className="tiny" style={{ marginTop: 12 }}>
              Generated by Deal Truth · open source · runs on PyAI
            </div>
          </div>
        </div>
      </AudioPlayerProvider>
    </EvidenceFocusProvider>
  );
}

export function DemoPage() {
  const calls = useCalls();
  if (calls.isLoading) return <PageSkeleton />;
  if (calls.isError) {
    return (
      <ErrorState
        title="Could not load demo call"
        description="The demo screen reads GET /api/v1/calls. Check that the API is reachable."
        onRetry={() => void calls.refetch()}
      />
    );
  }
  const call = pickDemoCall(calls.data?.items ?? []);
  if (!call) {
    return (
      <EmptyState
        title="No calls in the API yet"
        description="The demo does not ship a built-in record. Upload a recording, wait for the report, then open Demo again."
      />
    );
  }
  return <CallDetailPage callId={call.id} />;
}
